### ISSUE TITLE
Purpose of this package

### ISSUE THREAD

**Issue by de-vri-es** [ros-visualization/webkit_dependency#1]
I'm curious to the purpose of this package. I just encountered this a a dependency for `rqt_web`. Don't we have rosdep to find the right system dependencies for a given platform + ros distro?

Why should there be a package which in practise does nothing more than delegate to a rosdep key?

**Comment by dirk-thomas** [comment]
The problem is that depending on the ROS distribution we use a different Qt version. `rosdep` doesn't allow us to express a ROS distro specific mapping. It only has OS specific keys. Therefore this package ensures that you get the right system package for the ROS distro you use.

All this assumes that the downstream packages haven't branches for different ROS distros. Otherwise different rosdep keys could be used instead.

With all rqt plugins split into separate repos branching for example the `rqt_web` plugin would be much easier now. There are similar dependency packages for e.g. `gl` and those would require many more plugins to branch and maintain multiple branches in the future.

**Comment by de-vri-es** [comment]
hmm, I see. It seems a bit overkill to have a package for this, but I can see the benefit. Thanks for the answer.

It would be neat if rosdep could have distro specific mappings, but coordinating those mappings across different projects using the keys probably isn't feasible. Then again, the name `webkit_dependency` without prefix is also ROS wide, and not project specific.

Anyway, I got my answer. Thanks.
